In [1]:
import numpy as np

In [3]:
#1D array
#TASK1
HR_id = np.arange(1,4)
IT_id = np.arange(4,19)
Finance_id = np.arange(19,24)
Sales_id = np.arange(24,31)

In [7]:
print('HR_id:',HR_id)
print('IT_id:',IT_id)
print('Finance_id:',Finance_id)
print('Sales_id:',Sales_id)

HR_id: [1 2 3]
IT_id: [ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
Finance_id: [19 20 21 22 23]
Sales_id: [24 25 26 27 28 29 30]


In [105]:
#TASK2
HR_sal = np.array([50,60,57])
IT_sal = np.array([67]*15)
Finance_sal = np.array([60,65,50,70,87])
Sales_sal = np.array([50,60,65,90,56,65,71])

In [39]:
print("HR Salaries:", HR_sal)
print("IT Salaries:", IT_sal)
print("Finance Salaries:", Finance_sal)
print("Sales Salaries:", Sales_sal)

HR Salaries: [50 60 57]
IT Salaries: [67 67 67 67 67 67 67 67 67 67 67 67 67 67 67]
Finance Salaries: [60 65 50 70 87]
Sales Salaries: [50 60 65 90 56 65 71]


In [75]:
#TASK3
HR_salary = np.mean(HR_sal)
IT_salary = np.mean(IT_sal)
Finance_salary = np.mean(Finance_sal)
Sales_salary = np.mean(Sales_sal)
highest_sal = np.max([HR_salary,IT_salary,Finance_salary,Sales_salary])

The highest average salary is: 67.0


In [77]:
print('The average salary for HR is:',HR_salary)
print('The average salary for IT is:',IT_salary)
print('The average salary for Finance is:',Finance_salary)
print('The average salary for Sales is:',Sales_salary)
print('The highest average salary is:',highest_sal)
# the department with the highest average salary is IT with the average of 67.0

The average salary for HR is: 55.666666666666664
The average salary for IT is: 67.0
The average salary for Finance is: 66.4
The average salary for Sales is: 65.28571428571429
The highest average salary is: 67.0


In [41]:
#TASK4
hgt_hr_sal = np.max(HR_sal)
hgt_finance_sal = np.max(Finance_sal)

In [43]:
print('the highest salary in HR is:',hgt_hr_sal)
print('the highest salary in Finance is:',hgt_finance_sal)

the highest salary in HR is: 60
the highest salary in Finance is: 87


In [107]:
#TASK5
IT_sal= IT_sal*1.05
print('The updated salary for IT is:\n',IT_sal)

The updated salary for IT is:
 [70.35 70.35 70.35 70.35 70.35 70.35 70.35 70.35 70.35 70.35 70.35 70.35
 70.35 70.35 70.35]


In [53]:
#2D array
#TASK1
import numpy as np
from numpy import genfromtxt

In [57]:
adm_data = genfromtxt('DS1_C4_S1_AdmissionPredict_Data_Practice__1_.csv',
delimiter=',',skip_header=1)
print(adm_data)
print(np.size(adm_data[0:,0:]))

[[  1.   337.   118.   ...   9.65   1.     0.92]
 [  2.   324.   107.   ...   8.87   1.     0.76]
 [  3.   316.   104.   ...   8.     1.     0.72]
 ...
 [398.   330.   116.   ...   9.45   1.     0.91]
 [399.   312.   103.   ...   8.78   0.     0.67]
 [400.   333.   117.   ...   9.66   1.     0.95]]
3600


In [61]:
num_rows,num_col = adm_data.shape
print(adm_data.shape)

(400, 9)


In [63]:
#TASK2
print("The GRE score of all student is\n",adm_data[0:,1])

The GRE score of all student is
 [337. 324. 316. 322. 314. 330. 321. 308. 302. 323. 325. 327. 328. 307.
 311. 314. 317. 319. 318. 303. 312. 325. 328. 334. 336. 340. 322. 298.
 295. 310. 300. 327. 338. 340. 331. 320. 299. 300. 304. 307. 308. 316.
 313. 332. 326. 322. 329. 339. 321. 327. 313. 312. 334. 324. 322. 320.
 316. 298. 300. 311. 309. 307. 304. 315. 325. 325. 327. 316. 318. 328.
 332. 336. 321. 314. 314. 329. 327. 301. 296. 294. 312. 340. 320. 322.
 340. 319. 315. 317. 314. 316. 318. 299. 298. 301. 303. 304. 306. 331.
 332. 323. 322. 312. 314. 317. 326. 316. 329. 338. 331. 304. 305. 321.
 301. 320. 311. 310. 299. 290. 296. 327. 335. 334. 310. 308. 301. 300.
 323. 319. 326. 333. 339. 303. 309. 323. 333. 314. 312. 316. 326. 318.
 329. 332. 331. 340. 325. 320. 315. 326. 339. 311. 334. 332. 321. 324.
 326. 312. 315. 309. 306. 297. 315. 298. 318. 317. 329. 322. 302. 313.
 293. 311. 312. 334. 322. 323. 321. 320. 329. 319. 309. 307. 300. 305.
 299. 314. 316. 327. 317. 335. 331. 324. 324

In [65]:
#TASK3
Total_students=np.where(adm_data[0:,1]>320)
SIZE=np.size(Total_students)
print("The total students who's GRE score greater than 320 are ",SIZE)

The total students who's GRE score greater than 320 are  163


In [67]:
#TASK4
Toefl_score=np.where(adm_data[0:,2]>110)
# print(Toefl_score)
TOEFL=adm_data[Toefl_score,2]*100
print(TOEFL)

[[11800. 11500. 11100. 11200. 11400. 11600. 11900. 11900. 12000. 11800.
  11400. 11200. 11700. 11300. 11400. 11900. 11100. 11600. 11200. 11100.
  11200. 11400. 11500. 11800. 11200. 11100. 11400. 11200. 12000. 11500.
  11500. 12000. 11900. 11300. 11200. 11100. 11700. 11600. 11700. 11900.
  11300. 11200. 11200. 11800. 11400. 11200. 11300. 11600. 11800. 11500.
  12000. 11200. 11300. 11400. 11600. 11400. 11600. 11200. 11100. 11700.
  11300. 11100. 11100. 11900. 11300. 11800. 11500. 11200. 11100. 11400.
  11800. 12000. 12000. 12000. 11900. 11700. 11600. 11200. 11300. 11200.
  11100. 11300. 11100. 11200. 11400. 11500. 11400. 11100. 11500. 11400.
  11900. 11100. 11300. 11300. 11100. 11200. 11600. 11800. 11400. 12000.
  11400. 11200. 11200. 11100. 11300. 11600. 11200. 11300. 11100. 11800.
  11600. 11500. 11400. 11900. 11300. 11700. 11200. 11100. 11600. 11700.]]


In [73]:
#TASK5
students_eligible=np.where(adm_data[0:,1]>315) and np.where(adm_data[0:,2]>115)
print(students_eligible)
serial_number=adm_data[students_eligible,0]
print(serial_number)
print("The total number of students eligible for scholarship are:",np.size(serial_number))

(array([  0,  22,  23,  24,  25,  32,  43,  47,  52,  70,  81,  97,  98,
       107, 108, 120, 121, 129, 138, 141, 143, 148, 151, 171, 176, 187,
       193, 202, 203, 212, 213, 214, 215, 259, 285, 286, 297, 325, 337,
       361, 372, 385, 397, 399], dtype=int64),)
[[  1.  23.  24.  25.  26.  33.  44.  48.  53.  71.  82.  98.  99. 108.
  109. 121. 122. 130. 139. 142. 144. 149. 152. 172. 177. 188. 194. 203.
  204. 213. 214. 215. 216. 260. 286. 287. 298. 326. 338. 362. 373. 386.
  398. 400.]]
The total number of students eligible for scholarship are: 44
